### PR TITLE
Added solution for Reverse an array in C++

### PR DESCRIPTION
**Pull request by Gourav-78**
Solution added for Reverse an Array in C++
Related Issue : #18

### CODE REVIEW

**Review by OctoplusNinja — CHANGES_REQUESTED** [review]
can you remove the ".DS_Store" file? @Gourav-78

**Comment by Gourav-78** [comment]
> can you remove the ".DS_Store" file? @Gourav-78

Its happening becoz of my OS. MacOS automatically adds it when I create a folder or even migrate inside a folder

**Comment by OctoplusNinja** [comment]
@Gourav-78 , to fix that, make a ".gitignore" file and add a line ".DS_Store" (without the quotes) there. Then commit again.

**Comment by Gourav-78** [comment]
> @Gourav-78 , to fix that, make a ".gitignore" file and add a line ".DS_Store" (without the quotes) there. Then commit again.

.gitignore file in the repo right?

**Comment by OctoplusNinja** [comment]
> > @Gourav-78 , to fix that, make a ".gitignore" file and add a line ".DS_Store" (without the quotes) there. Then commit again.
> 
> .gitignore file in the repo right?

yes, that's right.

**Comment by Gourav-78** [comment]
> > > @Gourav-78 , to fix that, make a ".gitignore" file and add a line ".DS_Store" (without the quotes) there. Then commit again.
> > 
> > 
> > .gitignore file in the repo right?
> 
> yes, that's right.

I have added a pull request #65. Plz check that. If it is good to go then I will close this PR.

**Comment by OctoplusNinja** [comment]
Merged

**Pull request closed without merging**
