### PR TITLE
Create insertion_sort.py

### PR DESCRIPTION
**Pull request by BonkReaction**
Issue no.: #6

### CODE REVIEW

**Comment by BonkReaction** [comment]
@deepdhar @aman-raza lemme know if the commit is right and if so merge the PR as i've to other prs too.

**Comment by OctoplusNinja** [comment]
Merged your code @BonkReaction 🚀

**Comment by BonkReaction** [comment]
@aman-raza why you removed the `hacktoberfest accepted` label????

**Comment by aman-raza** [comment]
yours is merged you don't need this label
this was a mistake

**Pull request merged**
