### PR TITLE
Create CPP_Factorial_of_large_number.cpp

### PR DESCRIPTION
**Pull request by iamprofessor1**
Issue --> https://github.com/HacktoberfestSIT/Problem-Solving/issues/54
MY solution is 100%correct  written in CPP  ✔️✔️✔️✔️✔️
This code is able to calculate the factorial of more than 100 correctly 
I checked it 
Sir/Madam , Please check it .....
@OctoplusNinja

### CODE REVIEW

**Comment by iamprofessor1** [comment]
Sir /Madam , Please review it.
@OctoplusNinja

**Comment by OctoplusNinja** [comment]
hey @iamprofessor1 , can you add the files in proper folders, eg: array/Factorial_of_large_number/CPP/{your code}

**Comment by iamprofessor1** [comment]
Okay Sir /Madam @OctoplusNinja 
Please Check / review it

**Comment by OctoplusNinja** [comment]
@iamprofessor1 , you can delete the previous created file which is directly in the array folder.
image

Also, my pronouns are he/him/his. :)

**Comment by iamprofessor1** [comment]
@OctoplusNinja  Deleted

**Comment by OctoplusNinja** [comment]
Great, Merged 🚀!

**Pull request merged**
